[package]
name = "sol-burn"
version = "0.1.0"
edition = "2021"


[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.1"
figment = { version = "0.10.14", features = ["env"] }
log = "0.4.20"
serde = "1.0.196"
solana-sdk = "1.18.0"
solana-transaction-status = "1.18.0"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
jito-searcher-client = { path = "./searcher_client" }
jito-protos = { path = "./jito_protos" }
spl-token = "4.0.0"
tonic = "0.8.3"
futures-util = "0.3.30"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
